In [2]:
import pandas as pd

df = pd.read_csv("../../data/raw/transactions_data.csv", parse_dates=["date"])

In [22]:
data = df[['date', 'amount', 'use_chip', 'mcc', 'errors']]
data

                        date   amount            use_chip   mcc errors
0        2010-01-01 00:01:00  $-77.00   Swipe Transaction  5499    NaN
1        2010-01-01 00:02:00   $14.57   Swipe Transaction  5311    NaN
2        2010-01-01 00:02:00   $80.00   Swipe Transaction  4829    NaN
3        2010-01-01 00:05:00  $200.00   Swipe Transaction  4829    NaN
4        2010-01-01 00:06:00   $46.41   Swipe Transaction  5813    NaN
...                      ...      ...                 ...   ...    ...
13305910 2019-10-31 23:56:00    $1.11    Chip Transaction  5499    NaN
13305911 2019-10-31 23:56:00   $12.80  Online Transaction  5815    NaN
13305912 2019-10-31 23:57:00   $40.44   Swipe Transaction  4900    NaN
13305913 2019-10-31 23:58:00    $4.00    Chip Transaction  5411    NaN
13305914 2019-10-31 23:59:00   $12.88    Chip Transaction  5921    NaN

[13305915 rows x 5 columns]

In [23]:
import json

def traducir(x, dict):
    x = str(x)
    if x in dict:
        return dict[x]
    else:
        return 'Sin tipo'
        
def limpiar_error(e):
    if str(e) == 'nan':
        return 'Sin error'
    return e
        
def codificar_fecha(f):
    hora = f.hour
    minuto = f.minute
    return 60*hora+minuto

def madrugada(x):
    if x.hour < 7:
        return True
    return False
        


data['amount'] = data['amount'].map(lambda x: float(x[1:]))
with open('../../data/raw/mcc_codes.json', 'r') as file:
        dict_categorias = json.load(file)
data['mcc'] = data['mcc'].map(lambda x: traducir(x, dict_categorias))
data['errors'] = data['errors'].map(limpiar_error)
data['fecha_numerica'] = data['date'].map(codificar_fecha)
data['madrugada'] = data['date'].map(madrugada)
data['index'] = data.index.values
data

/tmp/ipykernel_13507/2304481649.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['amount'] = data['amount'].map(lambda x: float(x[1:]))
/tmp/ipykernel_13507/2304481649.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['mcc'] = data['mcc'].map(lambda x: traducir(x, dict_categorias))
/tmp/ipykernel_13507/2304481649.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['errors'] = data['errors'].map(limpiar_error)
/tmp/ipykernel_13507/2304481649.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['fecha_numerica'] = data['date'].map(codificar_fecha)
/tmp/ipykernel_13507/2304481649.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['madrugada'] = data['date'].map(madrugada)
/tmp/ipykernel_13507/2304481649.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['index'] = data.index.values

,date,amount,use_chip,mcc,errors,fecha_numerica,madrugada,index
0,2010-01-01 00:01:00,-77.00,Swipe Transaction,Miscellaneous Food Stores,Sin error,1,True,0
1,2010-01-01 00:02:00,14.57,Swipe Transaction,Department Stores,Sin error,2,True,1
2,2010-01-01 00:02:00,80.00,Swipe Transaction,Money Transfer,Sin error,2,True,2
3,2010-01-01 00:05:00,200.00,Swipe Transaction,Money Transfer,Sin error,5,True,3
4,2010-01-01 00:06:00,46.41,Swipe Transaction,Drinking Places (Alcoholic Beverages),Sin error,6,True,4
...,...,...,...,...,...,...,...,...
13305910,2019-10-31 23:56:00,1.11,Chip Transaction,Miscellaneous Food Stores,Sin error,1436,False,13305910
13305911,2019-10-31 23:56:00,12.80,Online Transaction,"Digital Goods - Media, Books, Apps",Sin error,1436,False,13305911
13305912,2019-10-31 23:57:00,40.44,Swipe Transaction,"Utilities - Electric, Gas, Water, Sanitary",Sin error,1437,False,13305912
13305913,2019-10-31 23:58:00,4.00,Chip Transaction,"Grocery Stores, Supermarkets",Sin error,1438,False,13305913
13305914,2019-10-31 23:59:00,12.88,Chip Transaction,"Package Stores, Beer, Wine, Liquor",Sin error,1439,False,13305914

In [17]:
from datetime import datetime
datetime.strptime('2019-10-31 23:56:00', '%Y-%m-%d %H:%M:%S').minute

56

In [24]:
data.to_csv('../../data/raw/train.csv', index=False)

In [2]:
import pandas as pd
train = pd.read_csv('../../data/raw/train.csv')

In [5]:
train['index'].values

array([       0,        1,        2, ..., 13305912, 13305913, 13305914])

In [3]:
import json
with open('../../data/raw/train_label_fraud.json', 'r') as f:
    d = json.load(f)
d

{'target': {'7475327': 'No',
  '7475328': 'No',
  '7475329': 'No',
  '7475332': 'No',
  '7475333': 'No',
  '7475335': 'No',
  '7475338': 'No',
  '7475339': 'No',
  '7475340': 'No',
  '7475341': 'No',
  '7475342': 'No',
  '7475344': 'No',
  '7475345': 'No',
  '7475346': 'No',
  '7475347': 'No',
  '7475348': 'No',
  '7475349': 'No',
  '7475350': 'No',
  '7475353': 'No',
  '7475354': 'No',
  '7475357': 'No',
  '7475359': 'No',
  '7475360': 'No',
  '7475361': 'No',
  '7475362': 'No',
  '7475363': 'No',
  '7475365': 'No',
  '7475366': 'No',
  '7475367': 'No',
  '7475368': 'No',
  '7475371': 'No',
  '7475372': 'No',
  '7475377': 'No',
  '7475378': 'No',
  '7475379': 'No',
  '7475380': 'No',
  '7475382': 'No',
  '7475383': 'No',
  '7475385': 'No',
  '7475389': 'No',
  '7475390': 'No',
  '7475394': 'No',
  '7475395': 'No',
  '7475398': 'No',
  '7475400': 'No',
  '7475401': 'No',
  '7475403': 'No',
  '7475406': 'No',
  '7475410': 'No',
  '7475411': 'No',
  '7475412': 'No',
  '7475414': 'No',
  '7475415': 'No',
  '7475417': 'No',
  '7475419': 'No',
  '7475420': 'No',
  '7475423': 'No',
  '7475424': 'No',
  '7475427': 'No',
  '7475429': 'No',
  '7475431': 'No',
  '7475432': 'No',
  '7475434': 'No',
  '7475436': 'No',
  '7475437': 'No',
  '7475439': 'No',
  '7475440': 'No',
  '7475442': 'No',
  '7475444': 'No',
  '7475446': 'No',
  '7475450': 'No',
  '7475452': 'No',
  '7475453': 'No',
  '7475456': 'No',
  '7475457': 'No',
  '7475458': 'No',
  '7475459': 'No',
  '7475460': 'No',
  '7475461': 'No',
  '7475462': 'No',
  '7475464': 'No',
  '7475465': 'No',
  '7475466': 'No',
  '7475468': 'No',
  '7475470': 'No',
  '7475471': 'No',
  '7475474': 'No',
  '7475476': 'No',
  '7475477': 'No',
  '7475478': 'No',
  '7475479': 'No',
  '7475480': 'No',
  '7475481': 'No',
  '7475485': 'No',
  '7475488': 'No',
  '7475489': 'No',
  '7475490': 'No',
  '7475491': 'No',
  '7475492': 'No',
  '7475495': 'No',
  '7475497': 'No',
  '7475498': 'No',
  '7475499': 'No',
  '7475501': 'No',
  '7475506': 'No',
  '7475511': 'No',
  '7475512': 'No',
  '7475514': 'No',
  '7475517': 'No',
  '7475518': 'No',
  '7475519': 'No',
  '7475521': 'No',
  '7475522': 'No',
  '7475523': 'No',
  '7475524': 'No',
  '7475526': 'No',
  '7475528': 'No',
  '7475529': 'No',
  '7475531': 'No',
  '7475532': 'No',
  '7475535': 'No',
  '7475537': 'No',
  '7475538': 'No',
  '7475539': 'No',
  '7475540': 'No',
  '7475546': 'No',
  '7475547': 'No',
  '7475551': 'No',
  '7475556': 'No',
  '7475559': 'No',
  '7475561': 'No',
  '7475564': 'No',
  '7475565': 'No',
  '7475567': 'No',
  '7475568': 'No',
  '7475569': 'No',
  '7475570': 'No',
  '7475571': 'No',
  '7475572': 'No',
  '7475573': 'No',
  '7475575': 'No',
  '7475576': 'No',
  '7475578': 'No',
  '7475579': 'No',
  '7475580': 'No',
  '7475584': 'No',
  '7475586': 'No',
  '7475588': 'No',
  '7475589': 'No',
  '7475590': 'No',
  '7475591': 'No',
  '7475592': 'No',
  '7475596': 'No',
  '7475598': 'No',
  '7475600': 'No',
  '7475601': 'No',
  '7475603': 'No',
  '7475604': 'No',
  '7475605': 'No',
  '7475606': 'No',
  '7475610': 'No',
  '7475611': 'No',
  '7475612': 'No',
  '7475616': 'No',
  '7475617': 'No',
  '7475622': 'No',
  '7475623': 'No',
  '7475624': 'No',
  '7475627': 'No',
  '7475628': 'No',
  '7475632': 'No',
  '7475633': 'No',
  '7475634': 'No',
  '7475635': 'No',
  '7475637': 'No',
  '7475638': 'No',
  '7475639': 'No',
  '7475640': 'No',
  '7475641': 'No',
  '7475642': 'No',
  '7475643': 'No',
  '7475644': 'No',
  '7475645': 'No',
  '7475646': 'No',
  '7475647': 'No',
  '7475648': 'No',
  '7475650': 'No',
  '7475651': 'No',
  '7475652': 'No',
  '7475658': 'No',
  '7475660': 'No',
  '7475661': 'No',
  '7475662': 'No',
  '7475663': 'No',
  '7475664': 'No',
  '7475665': 'No',
  '7475672': 'No',
  '7475673': 'No',
  '7475676': 'No',
  '7475679': 'No',
  '7475680': 'No',
  '7475681': 'No',
  '7475683': 'No',
  '7475684': 'No',
  '7475687': 'No',
  '7475688': 'No',
  '7475689': 'No',
  '7475692': 'No',
  '7475693': 'No',
  '7475694': 'No',
  '7475699': 'No',
  '7475700': 'No',
  '7475704': 'No',
  '7475705': 'No',
  '7475707': 'No',
  '7475711': 'No',
  '7475712': 'No',
  '7475714': 'No',
  '7475715': 'No',
  '7475717': 'No',
  '7475720': 'No',
  '7475721': 'No',
  '7475722': 'No',
  '7475723': 'No',
  '7475724': 'No',
  '7475726': 'No',
  '7475727': 'No',
  '7475728': 'No',
  '7475729': 'No',
  '7475730': 'No',
  '7475731': 'No',
  '7475735': 'No',
  '7475741': 'No',
  '7475742': 'No',
  '7475743': 'No',
  '7475744': 'No',
  '7475749': 'No',
  '7475750': 'No',
  '7475751': 'No',
  '7475753': 'No',
  '7475759': 'No',
  '7475760': 'No',
  '7475761': 'No',
  '7475762': 'No',
  '7475763': 'No',
  '7475766': 'No',
  '7475768': 'No',
  '7475770': 'No',
  '7475771': 'No',
  '7475773': 'No',
  '7475775': 'No',
  '7475776': 'No',
  '7475777': 'No',
  '7475779': 'No',
  '7475782': 'No',
  '7475783': 'No',
  '7475784': 'No',
  '7475785': 'No',
  '7475786': 'No',
  '7475787': 'No',
  '7475790': 'No',
  '7475791': 'No',
  '7475792': 'No',
  '7475793': 'No',
  '7475794': 'No',
  '7475799': 'No',
  '7475801': 'No',
  '7475802': 'No',
  '7475803': 'No',
  '7475804': 'No',
  '7475806': 'No',
  '7475807': 'No',
  '7475810': 'No',
  '7475811': 'No',
  '7475812': 'No',
  '7475813': 'No',
  '7475814': 'No',
  '7475815': 'No',
  '7475816': 'No',
  '7475819': 'No',
  '7475820': 'No',
  '7475821': 'No',
  '7475822': 'No',
  '7475823': 'No',
  '7475824': 'No',
  '7475825': 'No',
  '7475828': 'No',
  '7475830': 'No',
  '7475831': 'No',
  '7475832': 'No',
  '7475834': 'No',
  '7475836': 'No',
  '7475837': 'No',
  '7475839': 'No',
  '7475840': 'No',
  '7475841': 'No',
  '7475844': 'No',
  '7475845': 'No',
  '7475846': 'No',
  '7475847': 'No',
  '7475849': 'No',
  '7475850': 'No',
  '7475852': 'No',
  '7475854': 'No',
  '7475855': 'No',
  '7475856': 'No',
  '7475857': 'No',
  '7475860': 'No',
  '7475862': 'No',
  '7475863': 'No',
  '7475869': 'No',
  '7475870': 'No',
  '7475871': 'No',
  '7475872': 'No',
  '7475873': 'No',
  '7475874': 'No',
  '7475877': 'No',
  '7475878': 'No',
  '7475880': 'No',
  '7475881': 'No',
  '7475882': 'No',
  '7475884': 'No',
  '7475886': 'No',
  '7475887': 'No',
  '7475888': 'No',
  '7475889': 'No',
  '7475892': 'No',
  '7475897': 'No',
  '7475898': 'No',
  '7475900': 'No',
  '7475902': 'No',
  '7475903': 'No',
  '7475904': 'No',
  '7475909': 'No',
  '7475910': 'No',
  '7475911': 'No',
  '7475912': 'No',
  '7475914': 'No',
  '7475916': 'No',
  '7475920': 'No',
  '7475921': 'No',
  '7475922': 'No',
  '7475923': 'No',
  '7475926': 'No',
  '7475929': 'No',
  '7475930': 'No',
  '7475932': 'No',
  '7475934': 'No',
  '7475935': 'No',
  '7475936': 'No',
  '7475938': 'No',
  '7475941': 'No',
  '7475948': 'No',
  '7475951': 'No',
  '7475952': 'No',
  '7475955': 'No',
  '7475956': 'No',
  '7475959': 'No',
  '7475961': 'No',
  '7475964': 'No',
  '7475965': 'No',
  '7475969': 'No',
  '7475970': 'No',
  '7475971': 'No',
  '7475973': 'No',
  '7475975': 'No',
  '7475978': 'No',
  '7475979': 'No',
  '7475980': 'No',
  '7475981': 'No',
  '7475983': 'No',
  '7475984': 'No',
  '7475986': 'No',
  '7475988': 'No',
  '7475991': 'No',
  '7475992': 'No',
  '7475994': 'No',
  '7475995': 'No',
  '7475998': 'No',
  '7476000': 'No',
  '7476004': 'No',
  '7476006': 'No',
  '7476007': 'No',
  '7476009': 'No',
  '7476010': 'No',
  '7476013': 'No',
  '7476014': 'No',
  '7476015': 'No',
  '7476016': 'No',
  '7476018': 'No',
  '7476019': 'No',
  '7476021': 'No',
  '7476022': 'No',
  '7476023': 'No',
  '7476027': 'No',
  '7476029': 'No',
  '7476030': 'No',
  '7476031': 'No',
  '7476034': 'No',
  '7476038': 'No',
  '7476040': 'No',
  '7476041': 'No',
  '7476045': 'No',
  '7476046': 'No',
  '7476047': 'No',
  '7476049': 'No',
  '7476050': 'No',
  '7476051': 'No',
  '7476057': 'No',
  '7476058': 'No',
  '7476060': 'No',
  '7476061': 'No',
  '7476064': 'No',
  '7476068': 'No',
  '7476071': 'No',
  '7476073': 'No',
  '7476074': 'No',
  '7476077': 'No',
  '7476078': 'No',
  '7476080': 'No',
  '7476081': 'No',
  '7476084': 'No',
  '7476086': 'No',
  '7476091': 'No',
  '7476092': 'No',
  '7476093': 'No',
  '7476096': 'No',
  '7476097': 'No',
  '7476098': 'No',
  '7476100': 'No',
  '7476101': 'No',
  '7476104': 'No',
  '7476107': 'No',
  '7476111': 'No',
  '7476114': 'No',
  '7476116': 'No',
  '7476117': 'No',
  '7476118': 'No',
  '7476120': 'No',
  '7476121': 'No',
  '7476123': 'No',
  '7476126': 'No',
  '7476127': 'No',
  '7476128': 'No',
  '7476135': 'No',
  '7476137': 'No',
  '7476139': 'No',
  '7476141': 'No',
  '7476143': 'No',
  '7476144': 'No',
  '7476145': 'No',
  '7476146': 'No',
  '7476147': 'No',
  '7476150': 'No',
  '7476151': 'No',
  '7476155': 'No',
  '7476156': 'No',
  '7476157': 'No',
  '7476158': 'No',
  '7476159': 'No',
  '7476161': 'No',
  '7476162': 'No',
  '7476163': 'No',
  '7476164': 'No',
  '7476169': 'No',
  '7476173': 'No',
  '7476174': 'No',
  '7476177': 'No',
  '7476179': 'No',
  '7476180': 'No',
  '7476184': 'No',
  '7476187': 'No',
  '7476191': 'No',
  '7476192': 'No',
  '7476195': 'No',
  '7476196': 'No',
  '7476198': 'No',
  '7476202': 'No',
  '7476204': 'No',
  '7476205': 'No',
  '7476206': 'No',
  '7476208': 'No',
  '7476210': 'No',
  '7476211': 'No',
  '7476212': 'No',
  '7476213': 'No',
  '7476214': 'No',
  '7476215': 'No',
  '7476216': 'No',
  '7476218': 'No',
  '7476219': 'No',
  '7476221': 'No',
  '7476223': 'No',
  '7476229': 'No',
  '7476233': 'No',
  '7476235': 'No',
  '7476238': 'No',
  '7476239': 'No',
  '7476243': 'No',
  '7476244': 'No',
  '7476245': 'No',
  '7476248': 'No',
  '7476249': 'No',
  '7476252': 'No',
  '7476254': 'No',
  '7476257': 'No',
  '7476258': 'No',
  '7476259': 'No',
  '7476260': 'No',
  '7476261': 'No',
  '7476262': 'No',
  '7476263': 'No',
  '7476264': 'No',
  '7476268': 'No',
  '7476271': 'No',
  '7476273': 'No',
  '7476274': 'No',
  '7476275': 'No',
  '7476277': 'No',
  '7476278': 'No',
  '7476283': 'No',
  '7476285': 'No',
  '7476286': 'No',
  '7476288': 'No',
  '7476289': 'No',
  '7476290': 'No',
  '7476291': 'No',
  '7476292': 'No',
  '7476294': 'No',
  '7476295': 'No',
  '7476296': 'No',
  '7476297': 'No',
  '7476301': 'No',
  '7476302': 'No',
  '7476303': 'No',
  '7476306': 'No',
  '7476307': 'No',
  '7476308': 'No',
  '7476309': 'No',
  '7476312': 'No',
  '7476314': 'No',
  '7476315': 'No',
  '7476316': 'No',
  '7476317': 'No',
  '7476318': 'No',
  '7476319': 'No',
  '7476321': 'No',
  '7476323': 'No',
  '7476326': 'No',
  '7476327': 'No',
  '7476329': 'No',
  '7476330': 'No',
  '7476331': 'No',
  '7476332': 'No',
  '7476333': 'No',
  '7476334': 'No',
  '7476335': 'No',
  '7476339': 'No',
  '7476341': 'No',
  '7476343': 'No',
  '7476344': 'No',
  '7476345': 'No',
  '7476346': 'No',
  '7476348': 'No',
  '7476349': 'No',
  '7476350': 'No',
  '7476352': 'No',
  '7476357': 'No',
  '7476361': 'No',
  '7476363': 'No',
  '7476367': 'No',
  '7476368': 'No',
  '7476369': 'No',
  '7476370': 'No',
  '7476371': 'No',
  '7476372': 'No',
  '7476374': 'No',
  '7476375': 'No',
  '7476377': 'No',
  '7476379': 'No',
  '7476384': 'No',
  '7476386': 'No',
  '7476389': 'No',
  '7476391': 'No',
  '7476395': 'No',
  '7476396': 'No',
  '7476397': 'No',
  '7476398': 'No',
  '7476399': 'No',
  '7476401': 'No',
  '7476403': 'No',
  '7476405': 'No',
  '7476406': 'No',
  '7476407': 'No',
  '7476410': 'No',
  '7476412': 'No',
  '7476415': 'No',
  '7476419': 'No',
  '7476420': 'No',
  '7476422': 'No',
  '7476423': 'No',
  '7476425': 'No',
  '7476427': 'No',
  '7476429': 'No',
  '7476430': 'No',
  '7476432': 'No',
  '7476433': 'No',
  '7476434': 'No',
  '7476435': 'No',
  '7476436': 'No',
  '7476437': 'No',
  '7476439': 'No',
  '7476440': 'No',
  '7476442': 'No',
  '7476443': 'No',
  '7476444': 'No',
  '7476448': 'No',
  '7476451': 'No',
  '7476452': 'No',
  '7476453': 'No',
  '7476454': 'No',
  '7476455': 'No',
  '7476456': 'No',
  '7476457': 'No',
  '7476458': 'No',
  '7476459': 'No',
  '7476462': 'No',
  '7476464': 'No',
  '7476465': 'No',
  '7476467': 'No',
  '7476469': 'No',
  '7476470': 'No',
  '7476472': 'No',
  '7476473': 'No',
  '7476475': 'No',
  '7476476': 'No',
  '7476477': 'No',
  '7476480': 'No',
  '7476481': 'No',
  '7476482': 'No',
  '7476484': 'No',
  '7476485': 'No',
  '7476486': 'No',
  '7476487': 'No',
  '7476488': 'No',
  '7476489': 'No',
  '7476491': 'No',
  '7476493': 'No',
  '7476494': 'No',
  '7476495': 'No',
  '7476496': 'No',
  '7476500': 'No',
  '7476501': 'No',
  '7476503': 'No',
  '7476508': 'No',
  '7476509': 'No',
  '7476511': 'No',
  '7476515': 'No',
  '7476516': 'No',
  '7476517': 'No',
  '7476518': 'No',
  '7476519': 'No',
  '7476521': 'No',
  '7476522': 'No',
  '7476523': 'No',
  '7476524': 'No',
  '7476525': 'No',
  '7476526': 'No',
  '7476527': 'No',
  '7476528': 'No',
  '7476529': 'No',
  '7476532': 'No',
  '7476536': 'No',
  '7476537': 'No',
  '7476538': 'No',
  '7476539': 'No',
  '7476542': 'No',
  '7476545': 'No',
  '7476546': 'No',
  '7476547': 'No',
  '7476548': 'No',
  '7476549': 'No',
  '7476551': 'No',
  '7476554': 'No',
  '7476555': 'No',
  '7476557': 'No',
  '7476558': 'No',
  '7476559': 'No',
  '7476560': 'No',
  '7476563': 'No',
  '7476564': 'No',
  '7476565': 'No',
  '7476569': 'No',
  '7476571': 'No',
  '7476572': 'No',
  '7476573': 'No',
  '7476576': 'No',
  '7476577': 'No',
  '7476578': 'No',
  '7476581': 'No',
  '7476582': 'No',
  '7476583': 'No',
  '7476584': 'No',
  '7476588': 'No',
  '7476591': 'No',
  '7476592': 'No',
  '7476596': 'No',
  '7476601': 'No',
  '7476608': 'No',
  '7476609': 'No',
  '7476613': 'No',
  '7476615': 'No',
  '7476616': 'No',
  '7476617': 'No',
  '7476619': 'No',
  '7476621': 'No',
  '7476622': 'No',
  '7476623': 'No',
  '7476625': 'No',
  '7476627': 'No',
  '7476629': 'No',
  '7476630': 'No',
  '7476632': 'No',
  '7476634': 'No',
  '7476636': 'No',
  '7476638': 'No',
  '7476640': 'No',
  '7476643': 'No',
  '7476646': 'No',
  '7476647': 'No',
  '7476648': 'No',
  '7476649': 'No',
  '7476650': 'No',
  '7476653': 'No',
  '7476656': 'No',
  '7476657': 'No',
  '7476658': 'No',
  '7476662': 'No',
  '7476664': 'No',
  '7476666': 'No',
  '7476667': 'No',
  '7476668': 'No',
  '7476669': 'No',
  '7476670': 'No',
  '7476671': 'No',
  '7476672': 'No',
  '7476675': 'No',
  '7476676': 'No',
  '7476677': 'No',
  '7476679': 'No',
  '7476680': 'No',
  '7476683': 'No',
  '7476685': 'No',
  '7476686': 'No',
  '7476687': 'No',
  '7476689': 'No',
  '7476691': 'No',
  '7476692': 'No',
  '7476693': 'No',
  '7476694': 'No',
  '7476696': 'No',
  '7476697': 'No',
  '7476698': 'No',
  '7476699': 'No',
  '7476701': 'No',
  '7476704': 'No',
  '7476705': 'No',
  '7476707': 'No',
  '7476708': 'No',
  '7476709': 'No',
  '7476710': 'No',
  '7476712': 'No',
  '7476713': 'No',
  '7476716': 'No',
  '7476719': 'No',
  '7476720': 'No',
  '7476721': 'No',
  '7476723': 'No',
  '7476725': 'No',
  '7476728': 'No',
  '7476729': 'No',
  '7476730': 'No',
  '7476732': 'No',
  '7476733': 'No',
  '7476734': 'No',
  '7476736': 'No',
  '7476737': 'No',
  '7476738': 'No',
  '7476740': 'No',
  '7476741': 'No',
  '7476742': 'No',
  '7476743': 'No',
  '7476744': 'No',
  '7476745': 'No',
  '7476746': 'No',
  '7476747': 'No',
  '7476750': 'No',
  '7476751': 'No',
  '7476752': 'No',
  '7476753': 'No',
  '7476754': 'No',
  '7476755': 'No',
  '7476756': 'No',
  '7476758': 'No',
  '7476759': 'No',
  '7476763': 'No',
  '7476765': 'No',
  '7476769': 'No',
  '7476771': 'No',
  '7476772': 'No',
  '7476775': 'No',
  '7476776': 'No',
  '7476779': 'No',
  '7476780': 'No',
  '7476782': 'No',
  '7476785': 'No',
  '7476786': 'No',
  '7476788': 'No',
  '7476792': 'No',
  '7476794': 'No',
  '7476796': 'No',
  '7476798': 'No',
  '7476799': 'No',
  '7476800': 'No',
  '7476801': 'No',
  '7476802': 'No',
  '7476803': 'No',
  '7476804': 'No',
  '7476805': 'No',
  '7476809': 'No',
  '7476812': 'No',
  '7476813': 'No',
  '7476814': 'No',
  '7476815': 'No',
  '7476816': 'No',
  '7476818': 'No',
  '7476820': 'No',
  '7476821': 'No',
  '7476822': 'No',
  '7476824': 'No',
  '7476825': 'No',
  '7476826': 'No',
  '7476829': 'No',
  '7476835': 'No',
  '7476836': 'No',
  '7476837': 'No',
  '7476839': 'No',
  '7476840': 'No',
  '7476841': 'No',
  '7476842': 'No',
  '7476843': 'No',
  '7476844': 'No',
  '7476845': 'No',
  '7476846': 'No',
  '7476847': 'No',
  '7476848': 'No',
  '7476849': 'No',
  '7476852': 'No',
  '7476853': 'No',
  '7476854': 'No',
  '7476855': 'No',
  '7476861': 'No',
  '7476862': 'No',
  '7476863': 'No',
  '7476866': 'No',
  '7476867': 'No',
  '7476868': 'No',
  '7476870': 'No',
  '7476873': 'No',
  '7476874': 'No',
  '7476878': 'No',
  '7476879': 'No',
  '7476882': 'No',
  '7476883': 'No',
  '7476886': 'No',
  '7476887': 'No',
  '7476891': 'No',
  '7476892': 'No',
  '7476893': 'No',
  '7476894': 'No',
  '7476901': 'No',
  '7476905': 'No',
  '7476908': 'No',
  '7476910': 'No',
  '7476911': 'No',
  '7476912': 'No',
  '7476913': 'No',
  '7476917': 'No',
  '7476918': 'No',
  '7476919': 'No',
  '7476920': 'No',
  '7476921': 'No',
  '7476922': 'No',
  '7476923': 'No',
  '7476924': 'No',
  '7476925': 'No',
  '7476926': 'No',
  '7476928': 'No',
  '7476930': 'No',
  '7476931': 'No',
  '7476932': 'No',
  '7476933': 'No',
  '7476934': 'No',
  '7476935': 'No',
  '7476936': 'No',
  '7476937': 'No',
  '7476938': 'No',
  '7476940': 'No',
  '7476941': 'No',
  '7476943': 'No',
  '7476945': 'No',
  '7476948': 'No',
  '7476950': 'No',
  '7476952': 'No',
  '7476955': 'No',
  '7476958': 'No',
  '7476963': 'No',
  '7476965': 'No',
  '7476968': 'No',
  '7476969': 'No',
  '7476970': 'No',
  '7476974': 'No',
  '7476977': 'No',
  '7476984': 'No',
  '7476986': 'No',
  '7476987': 'No',
  '7476988': 'No',
  '7476993': 'No',
  '7476994': 'No',
  '7476995': 'No',
  '7476997': 'No',
  '7476998': 'No',
  '7476999': 'No',
  '7477001': 'No',
  '7477002': 'No',
  '7477005': 'No',
  '7477006': 'No',
  '7477007': 'No',
  '7477010': 'No',
  '7477011': 'No',
  '7477014': 'No',
  '7477017': 'No',
  '7477019': 'No',
  '7477020': 'No',
  '7477021': 'No',
  '7477022': 'No',
  '7477023': 'No',
  '7477025': 'No',
  '7477027': 'No',
  '7477032': 'No',
  '7477033': 'No',
  '7477034': 'No',
  '7477036': 'No',
  '7477037': 'No',
  '7477040': 'No',
  '7477041': 'No',
  '7477042': 'No',
  '7477043': 'No',
  '7477044': 'No',
  '7477046': 'No',
  '7477047': 'No',
  '7477048': 'No',
  '7477050': 'No',
  '7477055': 'No',
  '7477056': 'No',
  '7477059': 'No',
  '7477060': 'No',
  '7477062': 'No',
  '7477065': 'No',
  '7477066': 'No',
  '7477067': 'No',
  '7477068': 'No',
  '7477069': 'No',
  '7477070': 'No',
  '7477071': 'No',
  '7477073': 'No',
  '7477076': 'No',
  '7477077': 'No',
  '7477080': 'No',
  '7477082': 'No',
  '7477084': 'No',
  '7477088': 'No',
  '7477091': 'No',
  '7477092': 'No',
  '7477093': 'No',
  '7477094': 'No',
  '7477099': 'No',
  '7477100': 'No',
  '7477101': 'No',
  '7477102': 'No',
  '7477103': 'No',
  '7477105': 'No',
  '7477106': 'No',
  '7477107': 'No',
  '7477114': 'No',
  '7477115': 'No',
  '7477117': 'No',
  '7477118': 'No',
  '7477120': 'No',
  '7477122': 'No',
  ...}}

In [14]:
def encontrar_label(x,d):
    if str(x) in d['target']:
        return d['target'][str(x)]
    return 'No'

b = []
for i in train['index'].values:
    if str(i) in d['target']:
        b.append(True)
    else:
        b.append(False)

train_labeled = train[b]

train_labeled['label'] = train_labeled['index'].map(lambda x: encontrar_label(x, d))
train_labeled

/tmp/ipykernel_18842/4081394258.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_labeled['label'] = train_labeled['index'].map(lambda x: encontrar_label(x, d))

,date,amount,use_chip,mcc,errors,fecha_numerica,madrugada,index,label
7475327,2015-08-27 06:44:00,3.73,Chip Transaction,"Grocery Stores, Supermarkets",Sin error,404,True,7475327,No
7475328,2015-08-27 06:45:00,2.69,Chip Transaction,"Grocery Stores, Supermarkets",Sin error,405,True,7475328,No
7475329,2015-08-27 06:45:00,95.89,Chip Transaction,Miscellaneous Food Stores,Sin error,405,True,7475329,No
7475332,2015-08-27 06:46:00,3.72,Chip Transaction,Wholesale Clubs,Sin error,406,True,7475332,No
7475333,2015-08-27 06:46:00,14.34,Online Transaction,Taxicabs and Limousines,Sin error,406,True,7475333,No
...,...,...,...,...,...,...,...,...,...
13305903,2019-10-31 23:51:00,93.30,Chip Transaction,Wholesale Clubs,Sin error,1431,False,13305903,No
13305907,2019-10-31 23:55:00,11.43,Chip Transaction,Drinking Places (Alcoholic Beverages),Sin error,1435,False,13305907,No
13305909,2019-10-31 23:56:00,165.09,Chip Transaction,Telecommunication Services,Sin error,1436,False,13305909,No
13305911,2019-10-31 23:56:00,12.80,Online Transaction,"Digital Goods - Media, Books, Apps",Sin error,1436,False,13305911,No
13305912,2019-10-31 23:57:00,40.44,Swipe Transaction,"Utilities - Electric, Gas, Water, Sanitary",Sin error,1437,False,13305912,No

In [15]:
train_labeled['label'].unique()

array(['No', 'Yes'], dtype=object)

In [16]:
train_labeled.to_csv('../../data/raw/train_labeled.csv', index=False)

In [17]:
train_labeled.columns

Index(['date', 'amount', 'use_chip', 'mcc', 'errors', 'fecha_numerica',
       'madrugada', 'index', 'label'],
      dtype='object')

In [18]:
categorical_columns = ['use_chip', 'mcc', 'errors', 'madrugada']

df_encoded = train_labeled[['amount', 'use_chip', 'mcc', 'errors', 'fecha_numerica',
       'madrugada','label']]

df_encoded = pd.get_dummies(df_encoded, columns=categorical_columns)
df_encoded

,amount,fecha_numerica,madrugada,label,use_chip_Chip Transaction,use_chip_Online Transaction,use_chip_Swipe Transaction,"mcc_Accounting, Auditing, and Bookkeeping Services",mcc_Airlines,"mcc_Amusement Parks, Carnivals, Circuses",...,errors_Bad PIN,"errors_Bad PIN,Insufficient Balance","errors_Bad PIN,Technical Glitch",errors_Bad Zipcode,"errors_Bad Zipcode,Insufficient Balance","errors_Bad Zipcode,Technical Glitch",errors_Insufficient Balance,"errors_Insufficient Balance,Technical Glitch",errors_Sin error,errors_Technical Glitch
7475327,3.73,404,True,No,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
7475328,2.69,405,True,No,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
7475329,95.89,405,True,No,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
7475332,3.72,406,True,No,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
7475333,14.34,406,True,No,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13305903,93.30,1431,False,No,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
13305907,11.43,1435,False,No,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
13305909,165.09,1436,False,No,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
13305911,12.80,1436,False,No,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
13305912,40.44,1437,False,No,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,True,False

In [19]:
for col in df_encoded.columns:
    if col not in ['label']:
        df_encoded[col] = df_encoded[col].astype(float)

df_encoded

,amount,fecha_numerica,madrugada,label,use_chip_Chip Transaction,use_chip_Online Transaction,use_chip_Swipe Transaction,"mcc_Accounting, Auditing, and Bookkeeping Services",mcc_Airlines,"mcc_Amusement Parks, Carnivals, Circuses",...,errors_Bad PIN,"errors_Bad PIN,Insufficient Balance","errors_Bad PIN,Technical Glitch",errors_Bad Zipcode,"errors_Bad Zipcode,Insufficient Balance","errors_Bad Zipcode,Technical Glitch",errors_Insufficient Balance,"errors_Insufficient Balance,Technical Glitch",errors_Sin error,errors_Technical Glitch
7475327,3.73,404.0,1.0,No,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
7475328,2.69,405.0,1.0,No,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
7475329,95.89,405.0,1.0,No,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
7475332,3.72,406.0,1.0,No,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
7475333,14.34,406.0,1.0,No,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13305903,93.30,1431.0,0.0,No,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
13305907,11.43,1435.0,0.0,No,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
13305909,165.09,1436.0,0.0,No,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
13305911,12.80,1436.0,0.0,No,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
13305912,40.44,1437.0,0.0,No,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [20]:
df_encoded.to_csv('../../data/raw/train_num.csv', index=False)

In [ ]:
import pandas as pd
df_encoded = pd.read_csv('../../data/raw/train_num.csv')
short = df.iloc[:100000, :]
short.to_csv('../../data/raw/short_train.csv', index=False)

In [5]:
import pandas as pd
train_labeled = pd.read_csv('../../data/raw/train_labeled.csv')
train_labeled

,date,amount,use_chip,mcc,errors,fecha_numerica,madrugada,index,label
0,2015-08-27 06:44:00,3.73,Chip Transaction,"Grocery Stores, Supermarkets",Sin error,404,True,7475327,No
1,2015-08-27 06:45:00,2.69,Chip Transaction,"Grocery Stores, Supermarkets",Sin error,405,True,7475328,No
2,2015-08-27 06:45:00,95.89,Chip Transaction,Miscellaneous Food Stores,Sin error,405,True,7475329,No
3,2015-08-27 06:46:00,3.72,Chip Transaction,Wholesale Clubs,Sin error,406,True,7475332,No
4,2015-08-27 06:46:00,14.34,Online Transaction,Taxicabs and Limousines,Sin error,406,True,7475333,No
...,...,...,...,...,...,...,...,...,...
3216364,2019-10-31 23:51:00,93.30,Chip Transaction,Wholesale Clubs,Sin error,1431,False,13305903,No
3216365,2019-10-31 23:55:00,11.43,Chip Transaction,Drinking Places (Alcoholic Beverages),Sin error,1435,False,13305907,No
3216366,2019-10-31 23:56:00,165.09,Chip Transaction,Telecommunication Services,Sin error,1436,False,13305909,No
3216367,2019-10-31 23:56:00,12.80,Online Transaction,"Digital Goods - Media, Books, Apps",Sin error,1436,False,13305911,No
3216368,2019-10-31 23:57:00,40.44,Swipe Transaction,"Utilities - Electric, Gas, Water, Sanitary",Sin error,1437,False,13305912,No

In [6]:
categorical_columns = ['use_chip', 'mcc', 'errors', 'madrugada']

df_encoded = train_labeled[['amount', 'use_chip', 'mcc', 'errors', 'fecha_numerica',
       'madrugada','label']]

df_encoded = pd.get_dummies(df_encoded, columns=categorical_columns)
for col in df_encoded.columns:
    if col not in ['label']:
        df_encoded[col] = df_encoded[col].astype(float)

df_encoded

,amount,fecha_numerica,label,use_chip_Chip Transaction,use_chip_Online Transaction,use_chip_Swipe Transaction,"mcc_Accounting, Auditing, and Bookkeeping Services",mcc_Airlines,"mcc_Amusement Parks, Carnivals, Circuses",mcc_Antique Shops,...,"errors_Bad PIN,Technical Glitch",errors_Bad Zipcode,"errors_Bad Zipcode,Insufficient Balance","errors_Bad Zipcode,Technical Glitch",errors_Insufficient Balance,"errors_Insufficient Balance,Technical Glitch",errors_Sin error,errors_Technical Glitch,madrugada_False,madrugada_True
0,3.73,404.0,No,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1,2.69,405.0,No,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
2,95.89,405.0,No,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,3.72,406.0,No,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
4,14.34,406.0,No,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3216364,93.30,1431.0,No,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
3216365,11.43,1435.0,No,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
3216366,165.09,1436.0,No,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
3216367,12.80,1436.0,No,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
3216368,40.44,1437.0,No,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0

In [7]:
short = df_encoded.iloc[:1000000, :]
short.to_csv('../../data/raw/train_short.csv', index=False)